### ISSUE TITLE
Domain setting is not required

### ISSUE THREAD

**Issue by shadowhand** [ofbeaton/oauth2-phabricator#1]
The `$domain` property set [by the constructor](https://github.com/ofbeaton/oauth2-phabricator/blob/master/src/Provider/Phabricator.php#L38-L49) is not required. Any property that is `protected` (or `public`, but not recommended) can be set simply by setting the name in the `$options` array, as per [this code](https://github.com/thephpleague/oauth2-client/blob/18924c1b2e84dcddcb78a9bef4b9edc3c9e7d9ea/src/Provider/AbstractProvider.php#L111-L115).

**Comment by ofbeaton** [comment]
Thanks for the report.

**Comment by ofbeaton** [comment]
See additional fix for `domain`.
