### ISSUE TITLE
Access token can be set using query builder helper

### ISSUE THREAD

**Issue by shadowhand** [ofbeaton/oauth2-phabricator#2]
The [`buildQueryString`](https://github.com/thephpleague/oauth2-client/blob/18924c1b2e84dcddcb78a9bef4b9edc3c9e7d9ea/src/Tool/QueryBuilderTrait.php#L29) method is available for setting query strings. [This code](https://github.com/ofbeaton/oauth2-phabricator/blob/56c901637c261ce2fd883d6194ce01269df7ac6a/src/Provider/Phabricator.php#L87) can be replaced with:

```php
$url = $this->domain.self::PATH_API_USER.'?'.$this->buildQueryString([
    'access_token' => $token->getToken(),
]);
```

This will ensure that the token value is encoded properly for query strings, should the token contain unsafe characters.

**Comment by ofbeaton** [comment]
Thanks for the report and code submission.
