### ISSUE TITLE
Use array accessor to prevent undefined notices

### ISSUE THREAD

**Issue by shadowhand** [ofbeaton/oauth2-phabricator#3]
Instead of [directly accessing arrays](https://github.com/ofbeaton/oauth2-phabricator/blob/56c901637c261ce2fd883d6194ce01269df7ac6a/src/Provider/PhabricatorResourceOwner.php#L40) it is recommended to use the [`ArrayAccessorTrait`](https://github.com/thephpleague/oauth2-client/blob/18924c1b2e84dcddcb78a9bef4b9edc3c9e7d9ea/src/Tool/ArrayAccessorTrait.php) to fetch values. This prevents `E_NOTICE` warnings from being triggered by PHP when the key is undefined.

Sidenote: in PHP 7 we can use the [`??` null coalesce operator instead](http://lornajane.net/posts/2015/new-in-php-7-null-coalesce-operator).

**Comment by ofbeaton** [comment]
Thanks for the report. This was a direct copy of the code in thephpleague's official [oauth2-github's GithubResourceOwner](https://github.com/thephpleague/oauth2-github/blob/master/src/Provider/GithubResourceOwner.php) so you may want to report it there as well.

**Comment by shadowhand** [comment]
👍
